### ISSUE TITLE
Why  training on my own dataset start with a loss only 0.8..?

### ISSUE THREAD

**Issue by xxz-wow** [nianlonggu/MemSum#11]

**Comment by nianlonggu** [comment]
Hi,
see the definition of the loss https://github.com/nianlonggu/MemSum/blob/015ddda3878c209f0dfc7b19d783f9639b733ddb/src/MemSum_Full/train.py#L287

It may because of the reward (the Rouge score) is small, or the log probability is small. The latter can happen when the input document is short without too many sentences.

For me 0.8 looks normal, as long as the validation score is increasing.  For training detail with custom data please refer to the colab tutorial
https://github.com/nianlonggu/MemSum/blob/main/Data_processing_training_and_testing_for_MemSum.ipynb

**Comment by xxz-wow** [comment]
ok thank you！
